// Perler 官方色名参考其公开的 2025 Bead Color Reference。
// hex 是用于屏幕预览与近似匹配的数字参考，不代表实物在所有光照与批次下的精确颜色。
export const perlerPalette = {
  id: 'perler-standard-2025',
  brand: 'Perler',
  name: 'Perler 标准色（屏幕参考）',
  source: 'https://perler.com/content/uploaded_images/Perler_Bead-Color-Reference_2025.pdf',
  colors: [
    ['white', 'White', '白色', '#F4F4EF'],
    ['cream', 'Creme', '奶油色', '#F1E4C2'],
    ['sand', 'Sand', '沙色', '#D8B58A'],
    ['tan', 'Tan', '棕褐色', '#B8875E'],
    ['light-brown', 'Light Brown', '浅棕色', '#9A6547'],
    ['brown', 'Brown', '棕色', '#613E2C'],
    ['dark-brown', 'Dark Brown', '深棕色', '#3D2924'],
    ['peach', 'Peach', '蜜桃色', '#F3B38F'],
    ['blush', 'Blush', '腮红色', '#ED927E'],
    ['light-pink', 'Light Pink', '浅粉色', '#F3B7CD'],
    ['bubblegum', 'Bubblegum', '泡泡糖粉', '#EE78A8'],
    ['pink', 'Pink', '粉色', '#DA4E91'],
    ['raspberry', 'Raspberry', '覆盆子色', '#A93064'],
    ['plum', 'Plum', '李子色', '#73355E'],
    ['red', 'Red', '红色', '#D83B3E'],
    ['cranapple', 'Cranapple', '蔓越莓红', '#9D2735'],
    ['hot-coral', 'Hot Coral', '珊瑚红', '#F06055'],
    ['rust', 'Rust', '铁锈红', '#A9472D'],
    ['orange', 'Orange', '橙色', '#F37932'],
    ['cheddar', 'Cheddar', '切达橙', '#F5A623'],
    ['butterscotch', 'Butterscotch', '奶糖色', '#D88B2C'],
    ['yellow', 'Yellow', '黄色', '#F5D547'],
    ['pastel-yellow', 'Pastel Yellow', '粉彩黄', '#F5E88A'],
    ['prickly-pear', 'Prickly Pear', '仙人掌黄绿', '#C8D746'],
    ['kiwi-lime', 'Kiwi Lime', '奇异果绿', '#8BC34A'],
    ['pastel-green', 'Pastel Green', '粉彩绿', '#A8D69B'],
    ['light-green', 'Light Green', '浅绿色', '#70C486'],
    ['green', 'Green', '绿色', '#3C9B61'],
    ['shamrock', 'Shamrock', '三叶草绿', '#16845B'],
    ['dark-green', 'Dark Green', '深绿色', '#236044'],
    ['evergreen', 'Evergreen', '常青绿', '#194638'],
    ['parrot-green', 'Parrot Green', '鹦鹉绿', '#31A88A'],
    ['toothpaste', 'Toothpaste', '薄荷色', '#7DCEBE'],
    ['turquoise', 'Turquoise', '青绿色', '#27A8B5'],
    ['pastel-blue', 'Pastel Blue', '粉彩蓝', '#A7D7E8'],
    ['light-blue', 'Light Blue', '浅蓝色', '#5CB9DD'],
    ['periwinkle-blue', 'Periwinkle Blue', '长春花蓝', '#7587C9'],
    ['blueberry-cream', 'Blueberry Cream', '蓝莓奶油', '#8EA7D4'],
    ['cobalt', 'Cobalt', '钴蓝色', '#2866A3'],
    ['dark-blue', 'Dark Blue', '深蓝色', '#264B84'],
    ['midnight', 'Midnight', '午夜蓝', '#252C57'],
    ['pastel-lavender', 'Pastel Lavender', '粉彩薰衣草', '#C1A7D7'],
    ['purple', 'Purple', '紫色', '#76519B'],
    ['magenta', 'Magenta', '品红色', '#B63F8D'],
    ['light-grey', 'Light Grey', '浅灰色', '#C8C8C2'],
    ['grey', 'Grey', '灰色', '#858681'],
    ['dark-grey', 'Dark Grey', '深灰色', '#50524F'],
    ['black', 'Black', '黑色', '#242424'],
  ].map(([id, code, name, hex]) => ({ id, code, name, hex })),
}

export const palettes = [perlerPalette]

export function getPalette(id) {
  return palettes.find((palette) => palette.id === id) || palettes[0]
}
